requires 'perl' => '5.008005';
requires 'Dist::Zilla::Plugin::ConfirmRelease';
requires 'Dist::Zilla::Plugin::ExecDir';
requires 'Dist::Zilla::Plugin::FakeRelease';
requires 'Dist::Zilla::Plugin::GatherDir';
requires 'Dist::Zilla::Plugin::License';
requires 'Dist::Zilla::Plugin::MakeMaker';
requires 'Dist::Zilla::Plugin::Manifest';
requires 'Dist::Zilla::Plugin::ManifestSkip';
requires 'Dist::Zilla::Plugin::MetaJSON';
requires 'Dist::Zilla::Plugin::MetaYAML';
requires 'Dist::Zilla::Plugin::PruneCruft';
requires 'Dist::Zilla::Plugin::ReadmeAnyFromPod';
requires 'Dist::Zilla::Plugin::RunExtraTests';
requires 'Dist::Zilla::Plugin::ShareDir';
requires 'Dist::Zilla::Plugin::TestRelease';
requires 'Dist::Zilla::Plugin::UploadToCPAN';
requires 'Dist::Zilla::Role::PluginBundle::Config::Slicer';
requires 'Dist::Zilla::Role::PluginBundle::Easy';
requires 'Dist::Zilla::Role::PluginBundle::PluginRemover';
requires 'Moose';
requires 'namespace::clean';
test_requires 'Test::More' => '0.88';
